### ISSUE TITLE
Table Widgets render

### ISSUE THREAD

**Issue by shearichard** [prahladyeri/VisualAlchemist#12]
The rendering of the little green and red squares (which I think mark a unique column or a prime key column) seems a bit odd.

The green square appears, for a unique column, on the left hand end of the row and the red square appears over the word primary.

I'm looking at this on the latest Firefox on Windows 7 and possibly it may look differently elsewhere but this is what I've got .

![2015-06-25 11_18_47-visual alchemist](https://cloud.githubusercontent.com/assets/403435/8343683/14988f86-1b2c-11e5-99da-d83c5ae9e307.png)

**Comment by prahladyeri** [comment]
It's an issue with the way jsPlumb library works, nothing wrong with your browser. I am on my way towards fixing this bug, thanks for reporting.

**Comment by prahladyeri** [comment]
If you are still using Visual Alchemist by any chance, I've fixed this. Please test the latest master branch and let me know.

**Comment by prahladyeri** [comment]
Fixed in the latest update
