### ISSUE TITLE
Possibility of a CB mode?

### ISSUE THREAD

**Issue by lhausmann** [prahladyeri/VisualAlchemist#14]
I'm somewhat red-green colorblind and have a really hard time differentiating between the red and green dots. Maybe add an option to switch them to orange/blue or similar?

**Comment by prahladyeri** [comment]
Sure thing. Orange and blue are good defaults too. I'm good at programming, but actually new to UX design, hence the defaults. I'll change it to orange-blue soon. Thanks for the contribution.

**Comment by prahladyeri** [comment]
By any chance, if you are still using VA, I've fixed this in the latest master branch:

https://github.com/prahladyeri/VisualAlchemist/archive/master.zip

Let me know if the changed colors (orange for primary, blue for foreign keys) work for you.

**Comment by prahladyeri** [comment]
Closing this as issue is fixed in latest version.
