### ISSUE TITLE
Some nagging issues

### ISSUE THREAD

**Issue by prahladyeri** [prahladyeri/VisualAlchemist#25]
1. Fix copyright year in footer.
2. Test the header navbar in mobile view. Either remove the first logo text or switch to compact icon instead.
3. Create a relation, then while detaching it, drag the endpoint to a differ field. It will create a redundant endpoint which it shouldn't.
4. Add bkg color to bspopup dialog boxes title bar.

**Comment by calebmauer** [comment]
Have all these issues been resolved? From my testing I think they have unless I'm not understanding something.

**Comment by prahladyeri** [comment]
@calebmauer Yep, they are all fixed. Thanks for your contribution!
I'm closing this.
