### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by EmilMoe** [prahladyeri/VisualAlchemist#28]
Cool project, looking forward where this goes. Personally I hope for some integration with Laravels migrations.

You need to find a designer that will work along, right now it needs some touches to give it a really nice feel.

**Comment by prahladyeri** [comment]
@EmilMoe Thank you. Before adding any integration, this app needs to be modularized first. Presently, everything is in this huge god script called `app.js`. I'm thinking of using `BackBone.js` to create some structure.

You are right, I know nothing about designing and looks! Let me know if you can find one who is interested in this project.

**Comment by EmilMoe** [comment]
I'm not a perfect designer myself unfortunately. Flat themes are easier to handle though. Anyway first priority is functionality, not design. If you make it awesome functioning, I'm sure a designer will help you.

I agree that such thing as Laravel should be a plugin at its best.

**Comment by prahladyeri** [comment]
Thanks, @EmilMoe! 

Closing as this is technically not an issue.
