### ISSUE TITLE
UI Contribution

### ISSUE THREAD

**Issue by rmalcomber** [prahladyeri/VisualAlchemist#29]
Hey really like the project so far. 

Have you got a plan for improving the UI or can I contribute to that? I saw there isn't a mention of it on the Readme.

**Comment by prahladyeri** [comment]
Yes please, let me know if you have any plans for UI improvements. What area of VA do you think could be improved?

**Comment by rmalcomber** [comment]
Here's a list of thing I think would be good improvements. If any need clarification let me know. 

**Table Highlighting**
Click or tab(see keyboard shortcuts) on tables to select a table allowing the user to do table manipulations.

**Keyboard Shortcuts**
Adding keyboard shortcuts for adding tables, tabbing through current tables and table manipulations. Most developers hate going near the mouse. 

**Context Menu**
Right click menu for adding tables and table manipulation.

**Table Manipulation**
Renaming tables and adding columns. 
Adding functionailty to change column name, type, primary or unique without loading the table editor (Still keeping the table editor). 

**Misc**
The 'Code' button to be a dropdown button, with the output formats as sub children, I think it would be quicker than having the extra modal pop up asking. <- this change might be voided if there are export options in future versions. 
Personally I think the relationship line should be square'd instead of a bézier curve. 

Hope I've explained myself OK.
