### ISSUE TITLE
Support for Composite Primary Keys

### ISSUE THREAD

**Issue by calebmauer** [prahladyeri/VisualAlchemist#33]
Primary Composite Keys are not supported. This feature would allow one table to have multiple primary keys.

This actually might be supported for SQL Alchemy, I'm not sure. By I know it doesn't currently work with MySQL. 

I can add this feature unless there are objections.

[SO Question about multiple primary keys](http://stackoverflow.com/questions/217945/can-i-have-multiple-primary-keys-in-a-single-table)

**Comment by prahladyeri** [comment]
Closing as fixed.
