### ISSUE TITLE
Allow multiple foreign key constraints to point to the same field

### ISSUE THREAD

**Issue by calebmauer** [prahladyeri/VisualAlchemist#36]
Currently you can't have more that one field referencing a primary key field. For an example of where this causes problems, let's say you have a table called Colors, with a field called ColorName. If you have multiple tables that need to be able to reference the ColorName field, they wouldn;t be able to. This will prevent you from using the same table in multiple places. Drop down lists and related functionality won't work.

**Comment by prahladyeri** [comment]
@calebmauer Closing as you have fixed this.
