### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by arpit1997** [prahladyeri/VisualAlchemist#41]
Demo at this url http://visualalchemist.prahladyeri.com/ not working. It shows error on console when i tried to create table. 
```javascript
showAddTableDialog()
app.js:613 Uncaught ReferenceError: tables is not definedsuccess @ app.js:613(anonymous function) @ utils.js:359dispatch @ jquery.min.js:3r.handle @ jquery.min.js:3
```
Other than this code button also does not work
It throws this error
```javascript
app.js:562 Uncaught ReferenceError: tables is not defined
```
Any help ?

**Comment by pRivAte12** [comment]
Is this project alive? Still, i see the same error at demo url.
I wish to see the demo of this project

**Comment by prahladyeri** [comment]
@arpit1997 Please refresh and check, I've updated the demo site.

@pRivAte12 Yes, its very much alive. I was busy with some work since last few months, but back in action now!
