### ISSUE TITLE
What is valchemist.py functions?

### ISSUE THREAD

**Issue by richierh** [prahladyeri/VisualAlchemist#46]
Hi, I was trying valchemist.py and it's need flask .. so what is it actually?

**Comment by prahladyeri** [comment]
Its a very old project, I'd almost forgotten about it after it peaked interest some months ago. Basically I had tried to create a front-end (HTML/JavaScript/Bootstrap) App to create a diagramming functionality where you can build, drag and drop tables and join them using primary and foreign keys. I had also provided two output builders for `sqlalchemy` and `sqlite`, so you can seamlessly run them to create databases from the diagram output. But I guess, mostly everyone likes to work through code these days.

And no, it doesn't require a flask back-end. Its a static site, so you can put it on github sites too.
