### ISSUE TITLE
Regular Expression DoS vulnerability

### ISSUE THREAD

**Issue by yinxiL** [prahladyeri/VisualAlchemist#48]
We are working on the [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) problem and detected 1 vulnerable regex(es) from your repository.

1: ``^"(?:[^\n\f\r"\\]|\\(?:\r\n?|\n|\f)|\\[\S\s])*"`` in VisualAlchemist/lib/prettify/lang-css.js

Please try the following:

	var pattern = "^\"(?:[^\\n\\f\\r\"\\\\]|\\\\(?:\\r\\n?|\\n|\\f)|\\\\[\\S\\s])*\"";
	var input = "\"\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\\\n\n";
	var re = new RegExp(pattern);
	var matched = input.match(re);

We didn’t create a pull request because we're not sure if these cases are possible to take place in your program, we also do not understand the functionality of these regexes as you do. Thank you for your understanding.

**Comment by mullinmax** [comment]
Is this even really an issue? 
There isn't a backend server to effect right? 
So why not let users slow down their own computer?
