### ISSUE TITLE
Demo can't be accessed

### ISSUE THREAD

**Issue by eternalBlast** [prahladyeri/VisualAlchemist#49]
Hello, i see this project as an amazing project that helps database documentation, but the demo now can't be accessed. http://visualalchemist.prahladyeri.com/

**Comment by prahladyeri** [comment]
Thanks for bringing this out. I'm migrating my blog and domain from `prahladyeri.com` to `prahladyeri.github.io`, this is just a side effect of that. I'll soon shift the VA stuff to `prahladyeri.github.io/visualalchemist`.

**Comment by prahladyeri** [comment]
This project is being decommissioned due to lack of general interest and use. It will come back in another avatar in a better form soon, stay tuned.
